### ISSUE TITLE
Make this the canonical repo

### ISSUE THREAD

**Issue by srid** [GNUSim8085/GNUSim8085#1]
- [x] Push latest commits from SourceForge git repo to the master branch here
- [x] Retire SourceForge git repo
- [x] Point Launchpad project to this repo
- [x] Adjust URLs in the source code

**Comment by onkarshinde** [comment]
Launchpad doesn't allow importing from github branch. So I have just added reference in project description.

**Comment by srid** [comment]
Note that my Launchpad login no longer works (thanks to their messed up Ubuntu One migration), so I have no access to the Launchpad project. At one point we want to figure out what to do with the issues and forum posts over there.

**Comment by onkarshinde** [comment]
Closed sourceforge repo.

**Comment by onkarshinde** [comment]
Since the repo is up and running, are you happy to close this issue?
