### ISSUE TITLE
Error while installing GNUSim8085 in Mac OS 10.12.2

### ISSUE THREAD

**Issue by alvil** [GNUSim8085/GNUSim8085#13]
I navigated to the folder GNUSim8085-master and ran the command autoconf. Then when I ran the command ./configure  , I got the following error on my screen. 
<img width="863" alt="screen shot 2017-01-21 at 7 39 20 pm" src="https://cloud.githubusercontent.com/assets/10954124/22174998/38deff2c-e012-11e6-80c7-84c206b118fc.png">

**Comment by alvil** [comment]
After that if I run the command make , I get
make: *** No targets specified and no makefile found.  Stop.

Please help me with installation.

**Comment by alvil** [comment]
I rechecked the dependencies, removed configure and then when I ran autoconf , I get the following errors.I think the problem lies here
<img width="891" alt="screen shot 2017-01-22 at 11 45 29 am" src="https://cloud.githubusercontent.com/assets/10954124/22180530/5af83b2e-e098-11e6-9357-8803fefc2496.png">

**Comment by onkarshinde** [comment]
What is the version of automake on your machine? The minimum version required is 1.11.

**Comment by alvil** [comment]
its 1.15 .there has been an improvement. I have generated the configure file successfully and have ran the commands make and make install . I'm not sure whether the package is built. Where can I find the executable ?

**Comment by onkarshinde** [comment]
A bit difficult to tell how it works on OS X. Is there any directory called /usr/local/bin?

**Comment by onkarshinde** [comment]
The README and INSTALL are more geared towards installing from a source tarball. When working on git master better to just run ./autogen.sh before running configure.

**Comment by alvil** [comment]
yes. And I found the executable in /usr/local/bin and its perfectly working

**Comment by onkarshinde** [comment]
Can you take some screenshots similar to the ones here? - https://gnusim8085.github.io/screenshots
Also try running some programs and see if it is actually working. Try using the print function as well.

**Comment by alvil** [comment]
programs are working, that's what I meant by perfectly working.
<img width="1280" alt="screen shot 2017-01-22 at 1 10 38 pm" src="https://cloud.githubusercontent.com/assets/10954124/22180908/a2352c5c-e0a4-11e6-9b72-407cf9478459.png">
<img width="1280" alt="screen shot 2017-01-22 at 1 12 30 pm" src="https://cloud.githubusercontent.com/assets/10954124/22180909/a2c27dfa-e0a4-11e6-933a-290e476d6155.png">

**Comment by onkarshinde** [comment]
Looks a bit old fashioned. :-)
Where did you install the GTK+ development files from?

**Comment by fearthekarma** [comment]
From where did you installled gnu 8085 simulator can you share the download link??

**Comment by alvil** [comment]
Sorry I don't remember it. I simply googled it and I guess it was from sourceforge.net

**Comment by Himesh95** [comment]
I cloned the source, removed the configure file as stated by alvil.Till autoconf everything ran correctly.But when I run ./ configure it keeps telling error: config failed : gio not found.PS- I have checked all dependencies, gio and glib-2.0 are installed under /usr/local/lib/pkg-config.Please help

**Comment by onkarshinde** [comment]
@Himesh95 
Have you checked if PKG_CONFIG_PATH actually contains /use/local/lib/pkg-config on your machine?

**Comment by y4sh-patel** [comment]
Tried "make install" and got this error.
<img width="1280" alt="Screenshot 2021-01-06 at 3 58 10 PM" src="https://user-images.githubusercontent.com/56584149/103758539-55095e00-5038-11eb-9c37-311055d38484.png">
