### ISSUE TITLE
Instruction STAX does not support operand 'h'

### ISSUE THREAD

**Issue by tatsuvalue** [GNUSim8085/GNUSim8085#15]
in 8085-instructions.c (line 744-);

/* 12 STAX H */
static gint
_eef_inst_func_18 (eef_addr_t opnd_addr)
{
  return _eef_inst_func_stax (opnd_addr, 'D');
}

I guess that 'D' is 'H'.
  return _eef_inst_func_stax (opnd_addr, 'H');

(and need for code 'stax d')

**Comment by onkarshinde** [comment]
As far as I know there is no STAX H instruction in 8085 because STA stores the accumulator content to the memory location and address of the location is mentioned in HL pair.
The code you are referring to is meant for STAX D but the comment is wrong.

**Comment by tatsuvalue** [comment]
Thnaks!

I had forgot M operand for mov instruction (mov m, a).

"STAX H" equals "MOV M, A" (code 77h) ^^;
