### ISSUE TITLE
gnu8085 simulator

### ISSUE THREAD

**Issue by fearthekarma** [GNUSim8085/GNUSim8085#17]
Hey guys,
I am using macintosh and I am searching for gnu 8085 simulator for mac. Can anyone help me how can I install it in mac??

**Comment by onkarshinde** [comment]
Are you looking for a prepackaged binary? There isn't one. You need to download the source and compile from source.
You will also have to install the GTK libraries and development files from appropriate places. I believe HomeBrew project provides easy to install setup for GTK.

**Comment by onkarshinde** [comment]
@fearthekarma Have you managed to build the simulator from source?

**Comment by onkarshinde** [comment]
@fearthekarma Did you manage to build the simulator from source? I will close the issue if I don't get any reply by 15.

**Comment by onkarshinde** [comment]
The latest version now requires the GTK3 and GtkSourceView3.
Please make sure that you download the source of latest version from here and try.
https://gnusim8085.github.io/download
