### ISSUE TITLE
DLL files missing error

### ISSUE THREAD

**Issue by nikunj-r** [GNUSim8085/GNUSim8085#18]
When I run gnusim8085.exe it ask's for dll files. 
I am using Windows 8.1(64-bit).
I have downloaded gnusim8085-1.3.7.
Please help.

**Comment by onkarshinde** [comment]
Do you have the name of the DLL?

**Comment by nikunj-r** [comment]
I re-installed GNUSim8085 and the problem was solved. Thanks for your concern, appreciate it.
