### ISSUE TITLE
Simulator does not fit in to 1280x800 screen (win32+GTK2)

### ISSUE THREAD

**Issue by vitasam** [GNUSim8085/GNUSim8085#19]
Hi,
I have been trying the simulator on Acer Iconia WIn10 tablet (display size is 1280 x 800). The main window does not fit there - some of bottom UI elements are outside of the screen)

**Comment by onkarshinde** [comment]
Do you have screenshot for this so that I get an idea how it looks like?

**Comment by vitasam** [comment]
Hi,
it seems to be Ok now - everything fits to my tablet's screen

**Comment by onkarshinde** [comment]
Closed based on user feedback.
