### ISSUE TITLE
Community links

### ISSUE THREAD

**Issue by srid** [GNUSim8085/GNUSim8085#2]
Need a wiki page or something to collect all community contributions. Eg.: https://www.youtube.com/watch?v=_17kvlD20N0&list=PL_1-_Q4VI1SfM0ZTLx1lnOev8ENC9-RYx

**Comment by srid** [comment]
This can done in/ after #6

**Comment by onkarshinde** [comment]
Please refer to this new page - https://gnusim8085.github.io/community
I have included three video tutorials and one review link. If you are happy with the content then I will add the link to the page in top navigation.

**Comment by onkarshinde** [comment]
I have not heard any comment, so I assume you are fine with the content. I have added the link to new page in navigation.
