### ISSUE TITLE
Future of Windows build

### ISSUE THREAD

**Issue by onkarshinde** [GNUSim8085/GNUSim8085#23]
I have not found any way to get the Windows cross compilation build work with GTK3.

- Windows will have to stay on GTK 2 for the foreseeable future.
- Non-Windows build should move to GTK3 permanently. It does not make sense to maintain GTK2 build option for non-Windows platform.

In order to make code maintainable

- We should create a source subfolder for Windows
- Copy all the GUI related files to this folder
- Modify Makefile.am to use different files based on build type.

**Comment by onkarshinde** [comment]
@srid Your opinion please.

**Comment by srid** [comment]
What is the problem with GTK3 Windows build?

I'd rather entirely drop GTK2 support than end up having to maintain Windows specific GUI files.

**Comment by onkarshinde** [comment]
Our current Windows build mechanism is using mingw cross compiler and GTK2 pre-built binaries. There are no pre-built GTK3 binaries for Windows.
It may be possible to create a build using [MSYS2](http://www.msys2.org/) environment but I do not have access to a Windows machine to do any experiments.

**Comment by onkarshinde** [comment]
@srid Some good news. Fedora includes GTK3 binaries built with mingw. So it is possible to do cross compilation using these binaries and create GTK3 build for Windows.
I have now set up Fedora in virtual box machine. Will work on this in next few weeks.

**Comment by onkarshinde** [comment]
I have managed to get a build done on Fedora that includes all GTK3 and required libraries in one installer. But for some reason when this is installed some of the icons do not show up in UI. Looking at the log in console I can see issue loading icons from the theme.
I copied the entire Adwaita theme to installation folder and still could not resolve the issue.

After reading through lot of discussions on internet I have come across [EasyTAG](https://wiki.gnome.org/action/show/Apps/EasyTAG) application which uses almost same setup as us. The application is using GTK3, built for windows using Mingw and using NSIS to create installer. I am planning to look at how the installer is created for EasyTAG and see if we can borrow some of the logic.

**Comment by onkarshinde** [comment]
![gnusim8085_gtk3_windows_tested_in_wine](https://user-images.githubusercontent.com/5102265/42947638-6a4ae4a6-8b8b-11e8-84f7-a520611f640d.png)

@srid I have made good progress after lot of efforts and managed to create a installer build that includes all the dependencies. Please see the screenshot when I tested this using wine. Would you like to test this on a real Windows machine before I commit the changes? I can provide the installer in Google Drive.

**Comment by srid** [comment]
@onkarshinde I do not have a Windows machine, perhaps some of the interested Windows users would be willing to test the executable?

**Comment by onkarshinde** [comment]
![gnusim8085](https://user-images.githubusercontent.com/5102265/43019455-ac6cf078-8c7a-11e8-8d27-20f1a31a332e.PNG)

@srid Tested the application on a Windows 7 machine now. Please see the screenshot.

**Comment by srid** [comment]
Looks good to me!
