### ISSUE TITLE
Allow to load data in memory in hexadecimal format

### ISSUE THREAD

**Issue by enjis** [GNUSim8085/GNUSim8085#27]
![capture](https://user-images.githubusercontent.com/38658739/40280285-57628354-5c6e-11e8-9311-6077ad257bfd.PNG)

Does it only loads decimal numbers??

**Comment by onkarshinde** [comment]
Yes these fields currently only accept decimal values.

**Comment by onkarshinde** [comment]
@enjis 
I am working on adding a new column that can allow you to view and edit data in hex. The idea is to simply enter the value in hex format with without 'h'. For example 'AC' or '1A'.
Would you be willing to try code from git and provide feedback?
