### ISSUE TITLE
Direct addressing mode not working

### ISSUE THREAD

**Issue by SScattered** [GNUSim8085/GNUSim8085#33]
Whenever I try to use MOV A,00H program won't be compiled saying there's an error. I know that I can achieve what I wanted using lxi and using mov a,m but why this direct addressing mode doesn't work? Perhaps 8085 processor don't support it?

**Comment by onkarshinde** [comment]
The correct instruction to use is MVI and not MOV. Can you please try this?

**Comment by SScattered** [comment]
@onkarshinde yeah, I know about it. But recently my lecturer gave this mov a,00h. She said that when

mov a,00h
Inr a
sta 0060h

This will result in the value of memory address 01h will be stored in 0060h memory address. So I tried to do this. I know that inr increase the content by one, she said that accumulator holds memory address 01h in the end
