### ISSUE TITLE
Required GNU Sim 8085 software version 20140-04-02

### ISSUE THREAD

**Issue by insearch** [GNUSim8085/GNUSim8085#42]
We need to install " GNU Sim 8085 software version 20140-04-02" in our client's machine. Please avail us the software with installation guidelines. Please also let me know the software charges or installation charges if any. We agree to pay you the same.

Thanking You.

Your's Sincerely,
Navratan
+919932012167

**Comment by onkarshinde** [comment]
There are no charges to download or install this software. Can you please confirm what you are looking for exactly?

**Comment by insearch** [comment]
Dear Sir,
      I exactly need this version of software "GNU Sim 8085 software
version 20140-04-02" for installation at technical educational institution.
Please help me . My contact numbers are +919932012167 (Whatsapp and Mobile)
+913532500767 (Land Line).

Thanks & Regards

Navratan

**Comment by onkarshinde** [comment]
This software never had a version called 20140-04-02. Just download the latest release from the Code -> Releases section.
