### ISSUE TITLE
ADI instruction query

### ISSUE THREAD

**Issue by vamanose** [GNUSim8085/GNUSim8085#44]
What is the correct format for 8085 instruction below? It gets flagged as an error in the application.

ADI 'A'-'9'-1

I get two errors flagged for the above instruction.

"Undefined symbol"

and...

"Invalid operator or symbol. Check whether operands start with a number. e.g. a0H should be 0a0H."

Its probably expecting a different format, but not sure what.

**Comment by dawarhusain** [comment]
The format for `ADI` instruction is
```
ADI value
```
Here `value` is the *number* which you want to add into Accumulator.

I think the assembler has not been made to evaluate expressions as `value`. So `value` needs to be an integer, not an integer expression.

**Comment by onkarshinde** [comment]
As @dawarhusain mentioned you can not use expression for value. You can use variable though by declaring a value in advance using EQU pseudo operand. Please read the example in tutorial.
