### ISSUE TITLE
Build broken because of renaming README to README.md

### ISSUE THREAD

**Issue by onkarshinde** [GNUSim8085/GNUSim8085#5]
$ ./autogen.sh 
autoheader: WARNING: Using auxiliary files such as `acconfig.h', `config.h.bot'
autoheader: WARNING: and `config.h.top', to define templates for `config.h.in'
autoheader: WARNING: is deprecated and discouraged.
autoheader: 
autoheader: WARNING: Using the third argument of `AC_DEFINE' and
autoheader: WARNING: `AC_DEFINE_UNQUOTED' allows one to define a template without
autoheader: WARNING: `acconfig.h':
autoheader: 
autoheader: WARNING:   AC_DEFINE([NEED_FUNC_MAIN], 1,
autoheader: 		[Define if a function `main' is needed.])
autoheader: 
autoheader: WARNING: More sophisticated templates can also be produced, see the
autoheader: WARNING: documentation.
configure.ac:135: warning: The 'AM_PROG_MKDIR_P' macro is deprecated, and its use is discouraged.
configure.ac:135: You should use the Autoconf-provided 'AC_PROG_MKDIR_P' macro instead,
configure.ac:135: and use '$(MKDIR_P)' instead of '$(mkdir_p)'in your Makefile.am files.
Makefile.am: error: required file './README' not found

**Comment by srid** [comment]
Can this be easily fixed? It is nice to have rendered README on github.

**Comment by onkarshinde** [comment]
I can update build to use README.md where appropriate, but if the file becomes heavy with markdown then there may be further changes required to convert it to plain text when building.

**Comment by srid** [comment]
Feel free to make the necessary changes including reverting my commit (switching to markdown) if necessary.

We should look into hooking up Travis or Circle CI so PRs can be reviewed (whether build passes and test passes) before merging to prevent such regressions in future.

**Comment by srid** [comment]
Actually, for now I'll revert my README.md change so the build will pass once again.
