### ISSUE TITLE
I need a simulator for windows 7 or 10

### ISSUE THREAD

**Issue by salemsalamah** [GNUSim8085/GNUSim8085#50]

**Comment by srid** [comment]
There is `gnusim8085-1.4.1-installer.exe
` at https://github.com/GNUSim8085/GNUSim8085/releases

**Comment by salemsalamah** [comment]
Thanks alot


Sent from Yahoo Mail on Android 
 
  On الأحد, أغسطس ٩, ٢٠٢٠ at ١٢:٣٧ ص, Sridhar Ratnakumar<notifications@github.com> wrote:   


There is gnusim8085-1.4.1-installer.exe  at https://github.com/GNUSim8085/GNUSim8085/releases
