### ISSUE TITLE
Not obvious where the make command builds the binary

### ISSUE THREAD

**Issue by murtraja** [GNUSim8085/GNUSim8085#52]
Hello, 

I tried to follow the steps mentioned in the README and also went through the INSTALL file but after firing the make command, it was not obvious where the executable binary was built. In my limited experience using make, I was hoping for a bin directory to be created, but I couldn't find it. 

Since the make file was too long, I couldn't trace it there as well. At any rate, after looking at .gitignore, I found that the binary is present in the src directory. 

Please suggest a way in which we can make it easy for other people to contribute to this project. I am listing down some ways below

1. Add a CONTRIBUTING file which clearly states how to build, how to obtain a stack trace, how to debug, how to print debug statements, etc.
2. Make a bin folder which stores the binary and other build artefacts
3. Add the info in the INSTALL file

**Comment by onkarshinde** [comment]
If you follow standard make and make install command then the application will be installed under /user/local hierarchy. Don't see what is the problem here.
