### ISSUE TITLE
Setup new translation management tool

### ISSUE THREAD

**Issue by onkarshinde** [GNUSim8085/GNUSim8085#8]
Launchpad does not support importing files from github. So now we need to look for new translation management tool.
Weblate is my preferred choice. But suggest any other you may know.

- [x] Choose the translation tool
- [x] Request for hosting
- [x] Verify the hosting
- [x] Add weblate user as contributor
- [x] Verify the integration with github

**Comment by srid** [comment]
I have never worked with translation management tools, so I'd let you pick whatever is suitable for the project.

One thing you may want to consider is whether the translation tool integrates with GitHub. Eg: https://poeditor.com/help/how_to_translate_a_language_file_from_a_github_project

**Comment by onkarshinde** [comment]
I have used weblate in the past as translator. It has very simple no frills UI and the application itself is open source.
They have a hosted version which integrates with github. I have submitted request for our translations to be hosted. I will let you know when I receive response.

Meanwhile I have shut down the translations on launchpad.

**Comment by onkarshinde** [comment]
Can you please add 'weblate' user as contributor to the repository? This will allow the hosted version to push back translations to repository automatically.

**Comment by srid** [comment]
> Can you please add 'weblate' user as contributor to the repository?

done.

**Comment by onkarshinde** [comment]
Can you please confirm again if the weblate user have been added as contributor? (https://github.com/weblate)
I can't see it listed as member anywhere.

**Comment by HappyAndHarmless** [comment]
I added it under https://github.com/GNUSim8085/GNUSim8085/settings/collaboration and it is listed as "Awaiting weblate's response" (screenshot attached).

<img width="646" alt="screen shot 2016-10-09 at 12 06 55 pm" src="https://cloud.githubusercontent.com/assets/3998/19218490/f1364c5c-8e18-11e6-8a77-87d3ca782cdf.png">

**Comment by onkarshinde** [comment]
Ahh, I do not have access to the page. Is it only accessible to admins?

**Comment by HappyAndHarmless** [comment]
I gave you admin access now. Try again.

**Comment by onkarshinde** [comment]
The translations can now be managed using weblate hosted setup - https://hosted.weblate.org/projects/gnusim8085/translations/
We are at the last stage for this setup. The only thing remaining to be verified is automatic push of translations to github.

**Comment by onkarshinde** [comment]
The translations changes on weblate are now getting pushed to github. I will verify the updates from github to weblate tomorrow.

Meanwhile I have updated the website to make the contribute page visible. It now included details of the translation as well. Let me know if you have any comments.

**Comment by onkarshinde** [comment]
All set up is verified. Closing this.
