### ISSUE TITLE
Bump the versions of build dependencies

### ISSUE THREAD

**Issue by onkarshinde** [GNUSim8085/GNUSim8085#9]
For far too long we have supported very old versions of the various build dependencies like GTK, automake etc. We need to decide the support policy and bump the minimum version required once in a while. This will allow us to make use of new features in these tools (such as new widgets in GTK)

Current versioned build dependencies are:
- Automake >= 1.11
- GTK2 >= 2.24 or GTK3 >= 3.0.0
- GtkSourceView2 >= 2.10 or GtkSourceView3 >= 3.0
- gettext >= 0.18

I am proposing that we target Debian Stable/Ubuntu LTS (last supported), whichever is older, as our support platform.
As of today that means that we have to target Ubuntu 14.04. Note that even though Ubuntu 12.04 is active it is not supported on Desktop any more, only on server.

With Ubuntu 14.04 as target platform we get following minimum versions.
- **Automake >= 1.14**
- GTK2 >= 2.24 or **GTK3 >= 3.10**
- GtkSourceView2 >= 2.10 or **GtkSourceView3 >= 3.10**
- gettext >= 0.18

Please let me know if you agree with this proposal and I will bump the dependencies.

**Comment by HappyAndHarmless** [comment]
I agree 👍 

It makes sense to piggy-back on the stable release of Ubuntu LTS, at the least.

**Comment by onkarshinde** [comment]
I was mistaken about the support policy for Ubuntu releases. The LTS releases are now supported for 5 years on desktop as well.
https://www.ubuntu.com/info/release-end-of-life

This means that 12.04 is supported until April 2017. This gives us following minimum versions of the build dependencies.
* Automake >= 1.11
* GTK2 >= 2.24 or **GTK3 >= 3.4**
* GtkSourceView2 >= 2.10 or **GtkSourceView3 >= 3.4**
* gettext >= 0.18
